version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout

      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.mod" }}
      - run:
          name: Run unit tests
          command: |
            make test

      - run: make build

      - run: make run

      - save_cache:
          key: go-mod-v4-{{ checksum "go.mod" }}
          paths:
            - "/go/pkg/mod"

workflows:
  version: 2
  build-workflow:
    jobs:
      - build

